### PR TITLE
Feature one html css linters

### PR DESCRIPTION
**Pull request by Roathy**
In this branch I did:

- Add HTML file
- Add CSS file
- Add linters
- Edit README.file
- Edit .ignore file

### CODE REVIEW

**Review by Abenezer-Tilahun — CHANGES_REQUESTED** [review]
Hi @Roathy   , 

Great job for implemented  the some of the project requirement  , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.



almost

## Required Changes ♻️
_Check the comments below the review._

- [x] Kindly make sure that you Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git. Please make sure that Linter  set up correctly for this repository and Linter result should be green, this means that the last commit have a green check mark (✅) or a summary of the passed checks is in the PR. There should be no custom changes to linter config.
- [x] Kindly make sure that the repository looks professional , All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in a your's repo, The only optional section is FAQ. please Make sure the you added the section Future Features, including 1-3 potential features to be added.

- [x] Kindly make sure that Use descriptive commit messages - each commit should be small enough to describe it in one sentence. The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). So please make sure to fix the commit messages for future project.
- [x] Kindly make sure that Pull Request should have a descriptive title telling you what changes are inside and Pull Request should have a summary describing introduced changes in more detail. for more information look up this [document](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Roathy** [comment]
Hi @Abenezer-Tilahun , thank you for your feedback. I have already done some modifications to the project. Given the indication that we shall not create a new pull request and should keep working on the first one, What am I supposed to do now? Do I click on the button that says "Close with comment" or is there an additional step I need to follow to finish this activity?
Thank you

**Comment by Abenezer-Tilahun** [comment]
Hello @Roathy  Good Job for implementing the suggestion but before you submit for review Kindly makes sure that you addressed the following point .

- [x] your Pull Request should have a descriptive title telling you what changes are inside and Pull Request should have a summary describing introduced changes in more detail. for more information look up this [document](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md), Still your pull request is an empty shown below, to edit click on the three dot and you got an icon edit 
- Capture

- [x] This branch has conflict that should be resolved, so Kindly make sure that you resolved the conflict between your feature branch and main branch .

**Comment by Roathy** [comment]
Hi @Abenezer-Tilahun, thank you for your feedback. I think I have done all the fixes correctly this time, please let me know if everything is ok.
In case everything is OK, could you confirm to me if I need to send a new "Request Review" through the microverse dashboard; Or I simple need to end the pull request here and that would be enough.
Thanks

**Comment by Abenezer-Tilahun** [comment]
Hello @Roathy  Now you can submit for review.

**Review by braincee — COMMENTED** [review]
Hi @Roathy  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

youre-approved-shirley-auto-group

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
